import type { Translations } from "@/i18n/translations";
import { getDocumentationContent } from "./documentationContent";

/**
 * Generate and download documentation as a text file
 * (Using plain text instead of PDF to avoid external dependencies)
 */
export function generateDocumentationPdf(t: Translations): void {
  const sections = getDocumentationContent(t);

  // Build text content
  let textContent = "";

  // Cover page
  textContent += "AntiFraud Documentation\n";
  textContent += "By HTenterprise\n";
  textContent += "Digital fraud verification and prevention platform\n\n";
  textContent += "Version: 1.0\n";
  textContent += `Date: ${new Date().toISOString().split("T")[0]}\n`;
  textContent += "Contact: suporte.antifraud@gmail.com\n";
  textContent += `\n${"=".repeat(80)}\n\n`;

  // Table of contents
  textContent += "Table of Contents\n\n";
  for (let i = 0; i < sections.length; i++) {
    textContent += `${i + 1}. ${sections[i].title}\n`;
  }
  textContent += `\n${"=".repeat(80)}\n\n`;

  // Sections
  for (let i = 0; i < sections.length; i++) {
    textContent += `${i + 1}. ${sections[i].title}\n\n`;
    for (const item of sections[i].content) {
      textContent += `${item}\n\n`;
    }
    textContent += `${"=".repeat(80)}\n\n`;
  }

  // Footer
  textContent += "\n\nGenerated by AntiFraud - By HTenterprise\n";
  textContent += "Contact: suporte.antifraud@gmail.com\n";
  textContent += "Enhanced security powered by the ICP network\n";

  // Create blob and download
  const blob = new Blob([textContent], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `AntiFraud-Documentation-${new Date().toISOString().split("T")[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
