/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisError { 'message' : string, 'details' : [] | [string] }
export interface AnalysisRequest {
  'riskHistory' : [] | [Array<bigint>],
  'analyzerType' : RiskAnalyzerType,
  'data' : [] | [string],
  'target' : [] | [string],
  'businessProfile' : [] | [string],
}
export type AnalysisResponse = { 'result' : AnalysisResult } |
  { 'error' : AnalysisError };
export interface AnalysisResult {
  'riskHistory' : [] | [Array<bigint>],
  'explanation' : string,
  'score' : number,
  'businessProfile' : [] | [string],
  'recommendation' : string,
  'riskLevel' : string,
}
export interface ContactDetails {
  'id' : string,
  'verified' : string,
  'country' : string,
  'validationSource' : [] | [FieldSource],
  'type' : string,
  'trustScore' : string,
  'riskScoreDescription' : string,
  'trustScoreSource' : [] | [FieldSource],
  'countryValidationSource' : [] | [FieldSource],
  'address' : [] | [string],
  'reports' : string,
  'reportsSource' : [] | [FieldSource],
  'adjustedRiskScore' : [] | [string],
  'riskLevel' : string,
  'riskScore' : string,
  'adjustedRiskScoreSource' : [] | [FieldSource],
}
export interface ExtendedContactDetails {
  'content' : string,
  'contactType' : LookupProvider,
  'details' : ContactDetails,
}
export interface FieldSource { 'value' : string, 'sourceUrl' : string }
export type JoinSessionResult = { 'ok' : null } |
  { 'invalidCode' : null } |
  { 'sessionNotFound' : null };
export type JoinTokenValidationResult = { 'incorrectCode' : null } |
  { 'success' : null } |
  { 'invalidToken' : null } |
  { 'sessionNotFound' : null };
export interface Location { 'latitude' : number, 'longitude' : number }
export interface LocationShareError {
  'retryAfter' : [] | [bigint],
  'message' : string,
}
export type LocationShareResult = { 'error' : LocationShareError } |
  { 'success' : null } |
  { 'rateLimited' : RateLimitError };
export type LookupProvider = { 'numLookup' : null } |
  { 'custom' : string } |
  { 'google' : null } |
  { 'amazon' : null };
export interface ProviderConfig {
  'endpoint' : [] | [string],
  'name' : LookupProvider,
  'enabled' : boolean,
  'apiKey' : [] | [string],
}
export interface RateLimitError {
  'retryAfterSeconds' : bigint,
  'message' : string,
}
export interface RiskAnalysis {
  'riskHistory' : [] | [Array<bigint>],
  'explanation' : string,
  'score' : number,
  'businessProfile' : [] | [string],
  'recommendation' : string,
  'riskLevel' : string,
}
export type RiskAnalyzerType = { 'email' : null } |
  { 'crypto' : null } |
  { 'message' : null } |
  { 'phone' : null };
export interface RiskRequest {
  'riskHistory' : [] | [Array<bigint>],
  'analyzerType' : RiskAnalyzerType,
  'data' : [] | [string],
  'target' : [] | [string],
  'businessProfile' : [] | [string],
}
export type RiskResponse = { 'result' : RiskAnalysis } |
  { 'error' : AnalysisError };
export type SessionStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'stopped' : null } |
  { 'ended' : null };
export type TargetType = { 'email' : null } |
  { 'crypto' : null } |
  { 'message' : null } |
  { 'phoneNumber' : null };
export interface TermsDocument { 'legalText' : string, 'version' : string }
export interface TrustedContact {
  'id' : bigint,
  'verified' : string,
  'verificationDate' : [] | [string],
  'contactType' : string,
  'validationSource' : [] | [string],
  'name' : string,
  'extraInfo' : [] | [string],
  'trustScoreSource' : [] | [string],
  'details' : [] | [string],
  'reportsSource' : [] | [string],
  'riskLevel' : string,
  'lookupProvider' : string,
  'riskScore' : [] | [bigint],
  'normalizedContact' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ValidateCodeResult = { 'invalidCode' : null } |
  { 'success' : null } |
  { 'sessionNotFound' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrustedContact' : ActorMethod<[TrustedContact], bigint>,
  'analyze' : ActorMethod<[RiskRequest], RiskResponse>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCryptoReports' : ActorMethod<[string], undefined>,
  'clearPhoneReports' : ActorMethod<[string], undefined>,
  'clearTrustedContacts' : ActorMethod<[], undefined>,
  'createLocationShareSession' : ActorMethod<
    [string, string, string, string],
    [bigint, string, boolean]
  >,
  'endSession' : ActorMethod<[bigint], undefined>,
  'getAllTrustedContacts' : ActorMethod<[], Array<TrustedContact>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCryptoReports' : ActorMethod<[string], [] | [bigint]>,
  'getCurrentTerms' : ActorMethod<[], TermsDocument>,
  'getLookupDetails' : ActorMethod<[string], [] | [ExtendedContactDetails]>,
  'getPhoneReports' : ActorMethod<[string], [] | [bigint]>,
  'getProviderConfig' : ActorMethod<[string], [] | [ProviderConfig]>,
  'getSessionLocations' : ActorMethod<
    [bigint],
    [[] | [Location], [] | [Location]]
  >,
  'getSessionStatus' : ActorMethod<[bigint], SessionStatus>,
  'getTrustedContactById' : ActorMethod<[bigint], [] | [TrustedContact]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<[string], JoinSessionResult>,
  'oldAnalyze' : ActorMethod<[AnalysisRequest], AnalysisResponse>,
  'recordConsent' : ActorMethod<[bigint, string], boolean>,
  'report' : ActorMethod<[TargetType, string, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setProviderConfig' : ActorMethod<[string, ProviderConfig], undefined>,
  'stopSharing' : ActorMethod<[bigint], boolean>,
  'updateLocation' : ActorMethod<
    [bigint, string, Location],
    LocationShareResult
  >,
  'updateTerms' : ActorMethod<[TermsDocument], undefined>,
  'validateJoinToken' : ActorMethod<
    [string, string],
    JoinTokenValidationResult
  >,
  'validateSessionCode' : ActorMethod<[bigint, string], ValidateCodeResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];