/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TrustedContact = IDL.Record({
  'id' : IDL.Nat,
  'verified' : IDL.Text,
  'verificationDate' : IDL.Opt(IDL.Text),
  'contactType' : IDL.Text,
  'validationSource' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'extraInfo' : IDL.Opt(IDL.Text),
  'trustScoreSource' : IDL.Opt(IDL.Text),
  'details' : IDL.Opt(IDL.Text),
  'reportsSource' : IDL.Opt(IDL.Text),
  'riskLevel' : IDL.Text,
  'lookupProvider' : IDL.Text,
  'riskScore' : IDL.Opt(IDL.Nat),
  'normalizedContact' : IDL.Text,
});
export const RiskAnalyzerType = IDL.Variant({
  'email' : IDL.Null,
  'crypto' : IDL.Null,
  'message' : IDL.Null,
  'phone' : IDL.Null,
});
export const RiskRequest = IDL.Record({
  'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'analyzerType' : RiskAnalyzerType,
  'data' : IDL.Opt(IDL.Text),
  'target' : IDL.Opt(IDL.Text),
  'businessProfile' : IDL.Opt(IDL.Text),
});
export const RiskAnalysis = IDL.Record({
  'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'explanation' : IDL.Text,
  'score' : IDL.Float64,
  'businessProfile' : IDL.Opt(IDL.Text),
  'recommendation' : IDL.Text,
  'riskLevel' : IDL.Text,
});
export const AnalysisError = IDL.Record({
  'message' : IDL.Text,
  'details' : IDL.Opt(IDL.Text),
});
export const RiskResponse = IDL.Variant({
  'result' : RiskAnalysis,
  'error' : AnalysisError,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TermsDocument = IDL.Record({
  'legalText' : IDL.Text,
  'version' : IDL.Text,
});
export const LookupProvider = IDL.Variant({
  'numLookup' : IDL.Null,
  'custom' : IDL.Text,
  'google' : IDL.Null,
  'amazon' : IDL.Null,
});
export const FieldSource = IDL.Record({
  'value' : IDL.Text,
  'sourceUrl' : IDL.Text,
});
export const ContactDetails = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Text,
  'country' : IDL.Text,
  'validationSource' : IDL.Opt(FieldSource),
  'type' : IDL.Text,
  'trustScore' : IDL.Text,
  'riskScoreDescription' : IDL.Text,
  'trustScoreSource' : IDL.Opt(FieldSource),
  'countryValidationSource' : IDL.Opt(FieldSource),
  'address' : IDL.Opt(IDL.Text),
  'reports' : IDL.Text,
  'reportsSource' : IDL.Opt(FieldSource),
  'adjustedRiskScore' : IDL.Opt(IDL.Text),
  'riskLevel' : IDL.Text,
  'riskScore' : IDL.Text,
  'adjustedRiskScoreSource' : IDL.Opt(FieldSource),
});
export const ExtendedContactDetails = IDL.Record({
  'content' : IDL.Text,
  'contactType' : LookupProvider,
  'details' : ContactDetails,
});
export const ProviderConfig = IDL.Record({
  'endpoint' : IDL.Opt(IDL.Text),
  'name' : LookupProvider,
  'enabled' : IDL.Bool,
  'apiKey' : IDL.Opt(IDL.Text),
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'stopped' : IDL.Null,
  'ended' : IDL.Null,
});
export const JoinSessionResult = IDL.Variant({
  'ok' : IDL.Null,
  'invalidCode' : IDL.Null,
  'sessionNotFound' : IDL.Null,
});
export const AnalysisRequest = IDL.Record({
  'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'analyzerType' : RiskAnalyzerType,
  'data' : IDL.Opt(IDL.Text),
  'target' : IDL.Opt(IDL.Text),
  'businessProfile' : IDL.Opt(IDL.Text),
});
export const AnalysisResult = IDL.Record({
  'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'explanation' : IDL.Text,
  'score' : IDL.Float64,
  'businessProfile' : IDL.Opt(IDL.Text),
  'recommendation' : IDL.Text,
  'riskLevel' : IDL.Text,
});
export const AnalysisResponse = IDL.Variant({
  'result' : AnalysisResult,
  'error' : AnalysisError,
});
export const TargetType = IDL.Variant({
  'email' : IDL.Null,
  'crypto' : IDL.Null,
  'message' : IDL.Null,
  'phoneNumber' : IDL.Null,
});
export const LocationShareError = IDL.Record({
  'retryAfter' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
});
export const RateLimitError = IDL.Record({
  'retryAfterSeconds' : IDL.Nat,
  'message' : IDL.Text,
});
export const LocationShareResult = IDL.Variant({
  'error' : LocationShareError,
  'success' : IDL.Null,
  'rateLimited' : RateLimitError,
});
export const JoinTokenValidationResult = IDL.Variant({
  'incorrectCode' : IDL.Null,
  'success' : IDL.Null,
  'invalidToken' : IDL.Null,
  'sessionNotFound' : IDL.Null,
});
export const ValidateCodeResult = IDL.Variant({
  'invalidCode' : IDL.Null,
  'success' : IDL.Null,
  'sessionNotFound' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrustedContact' : IDL.Func([TrustedContact], [IDL.Nat], []),
  'analyze' : IDL.Func([RiskRequest], [RiskResponse], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCryptoReports' : IDL.Func([IDL.Text], [], []),
  'clearPhoneReports' : IDL.Func([IDL.Text], [], []),
  'clearTrustedContacts' : IDL.Func([], [], []),
  'createLocationShareSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat, IDL.Text, IDL.Bool],
      [],
    ),
  'endSession' : IDL.Func([IDL.Nat], [], []),
  'getAllTrustedContacts' : IDL.Func([], [IDL.Vec(TrustedContact)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCryptoReports' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getCurrentTerms' : IDL.Func([], [TermsDocument], ['query']),
  'getLookupDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ExtendedContactDetails)],
      ['query'],
    ),
  'getPhoneReports' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getProviderConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProviderConfig)],
      ['query'],
    ),
  'getSessionLocations' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Location), IDL.Opt(Location)],
      ['query'],
    ),
  'getSessionStatus' : IDL.Func([IDL.Nat], [SessionStatus], ['query']),
  'getTrustedContactById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(TrustedContact)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Text], [JoinSessionResult], []),
  'oldAnalyze' : IDL.Func([AnalysisRequest], [AnalysisResponse], ['query']),
  'recordConsent' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'report' : IDL.Func([TargetType, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setProviderConfig' : IDL.Func([IDL.Text, ProviderConfig], [], []),
  'stopSharing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateLocation' : IDL.Func(
      [IDL.Nat, IDL.Text, Location],
      [LocationShareResult],
      [],
    ),
  'updateTerms' : IDL.Func([TermsDocument], [], []),
  'validateJoinToken' : IDL.Func(
      [IDL.Text, IDL.Text],
      [JoinTokenValidationResult],
      [],
    ),
  'validateSessionCode' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [ValidateCodeResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TrustedContact = IDL.Record({
    'id' : IDL.Nat,
    'verified' : IDL.Text,
    'verificationDate' : IDL.Opt(IDL.Text),
    'contactType' : IDL.Text,
    'validationSource' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'extraInfo' : IDL.Opt(IDL.Text),
    'trustScoreSource' : IDL.Opt(IDL.Text),
    'details' : IDL.Opt(IDL.Text),
    'reportsSource' : IDL.Opt(IDL.Text),
    'riskLevel' : IDL.Text,
    'lookupProvider' : IDL.Text,
    'riskScore' : IDL.Opt(IDL.Nat),
    'normalizedContact' : IDL.Text,
  });
  const RiskAnalyzerType = IDL.Variant({
    'email' : IDL.Null,
    'crypto' : IDL.Null,
    'message' : IDL.Null,
    'phone' : IDL.Null,
  });
  const RiskRequest = IDL.Record({
    'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'analyzerType' : RiskAnalyzerType,
    'data' : IDL.Opt(IDL.Text),
    'target' : IDL.Opt(IDL.Text),
    'businessProfile' : IDL.Opt(IDL.Text),
  });
  const RiskAnalysis = IDL.Record({
    'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'explanation' : IDL.Text,
    'score' : IDL.Float64,
    'businessProfile' : IDL.Opt(IDL.Text),
    'recommendation' : IDL.Text,
    'riskLevel' : IDL.Text,
  });
  const AnalysisError = IDL.Record({
    'message' : IDL.Text,
    'details' : IDL.Opt(IDL.Text),
  });
  const RiskResponse = IDL.Variant({
    'result' : RiskAnalysis,
    'error' : AnalysisError,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TermsDocument = IDL.Record({
    'legalText' : IDL.Text,
    'version' : IDL.Text,
  });
  const LookupProvider = IDL.Variant({
    'numLookup' : IDL.Null,
    'custom' : IDL.Text,
    'google' : IDL.Null,
    'amazon' : IDL.Null,
  });
  const FieldSource = IDL.Record({
    'value' : IDL.Text,
    'sourceUrl' : IDL.Text,
  });
  const ContactDetails = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Text,
    'country' : IDL.Text,
    'validationSource' : IDL.Opt(FieldSource),
    'type' : IDL.Text,
    'trustScore' : IDL.Text,
    'riskScoreDescription' : IDL.Text,
    'trustScoreSource' : IDL.Opt(FieldSource),
    'countryValidationSource' : IDL.Opt(FieldSource),
    'address' : IDL.Opt(IDL.Text),
    'reports' : IDL.Text,
    'reportsSource' : IDL.Opt(FieldSource),
    'adjustedRiskScore' : IDL.Opt(IDL.Text),
    'riskLevel' : IDL.Text,
    'riskScore' : IDL.Text,
    'adjustedRiskScoreSource' : IDL.Opt(FieldSource),
  });
  const ExtendedContactDetails = IDL.Record({
    'content' : IDL.Text,
    'contactType' : LookupProvider,
    'details' : ContactDetails,
  });
  const ProviderConfig = IDL.Record({
    'endpoint' : IDL.Opt(IDL.Text),
    'name' : LookupProvider,
    'enabled' : IDL.Bool,
    'apiKey' : IDL.Opt(IDL.Text),
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'stopped' : IDL.Null,
    'ended' : IDL.Null,
  });
  const JoinSessionResult = IDL.Variant({
    'ok' : IDL.Null,
    'invalidCode' : IDL.Null,
    'sessionNotFound' : IDL.Null,
  });
  const AnalysisRequest = IDL.Record({
    'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'analyzerType' : RiskAnalyzerType,
    'data' : IDL.Opt(IDL.Text),
    'target' : IDL.Opt(IDL.Text),
    'businessProfile' : IDL.Opt(IDL.Text),
  });
  const AnalysisResult = IDL.Record({
    'riskHistory' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'explanation' : IDL.Text,
    'score' : IDL.Float64,
    'businessProfile' : IDL.Opt(IDL.Text),
    'recommendation' : IDL.Text,
    'riskLevel' : IDL.Text,
  });
  const AnalysisResponse = IDL.Variant({
    'result' : AnalysisResult,
    'error' : AnalysisError,
  });
  const TargetType = IDL.Variant({
    'email' : IDL.Null,
    'crypto' : IDL.Null,
    'message' : IDL.Null,
    'phoneNumber' : IDL.Null,
  });
  const LocationShareError = IDL.Record({
    'retryAfter' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
  });
  const RateLimitError = IDL.Record({
    'retryAfterSeconds' : IDL.Nat,
    'message' : IDL.Text,
  });
  const LocationShareResult = IDL.Variant({
    'error' : LocationShareError,
    'success' : IDL.Null,
    'rateLimited' : RateLimitError,
  });
  const JoinTokenValidationResult = IDL.Variant({
    'incorrectCode' : IDL.Null,
    'success' : IDL.Null,
    'invalidToken' : IDL.Null,
    'sessionNotFound' : IDL.Null,
  });
  const ValidateCodeResult = IDL.Variant({
    'invalidCode' : IDL.Null,
    'success' : IDL.Null,
    'sessionNotFound' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrustedContact' : IDL.Func([TrustedContact], [IDL.Nat], []),
    'analyze' : IDL.Func([RiskRequest], [RiskResponse], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCryptoReports' : IDL.Func([IDL.Text], [], []),
    'clearPhoneReports' : IDL.Func([IDL.Text], [], []),
    'clearTrustedContacts' : IDL.Func([], [], []),
    'createLocationShareSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat, IDL.Text, IDL.Bool],
        [],
      ),
    'endSession' : IDL.Func([IDL.Nat], [], []),
    'getAllTrustedContacts' : IDL.Func(
        [],
        [IDL.Vec(TrustedContact)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCryptoReports' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getCurrentTerms' : IDL.Func([], [TermsDocument], ['query']),
    'getLookupDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ExtendedContactDetails)],
        ['query'],
      ),
    'getPhoneReports' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getProviderConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProviderConfig)],
        ['query'],
      ),
    'getSessionLocations' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Location), IDL.Opt(Location)],
        ['query'],
      ),
    'getSessionStatus' : IDL.Func([IDL.Nat], [SessionStatus], ['query']),
    'getTrustedContactById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TrustedContact)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Text], [JoinSessionResult], []),
    'oldAnalyze' : IDL.Func([AnalysisRequest], [AnalysisResponse], ['query']),
    'recordConsent' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'report' : IDL.Func([TargetType, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setProviderConfig' : IDL.Func([IDL.Text, ProviderConfig], [], []),
    'stopSharing' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateLocation' : IDL.Func(
        [IDL.Nat, IDL.Text, Location],
        [LocationShareResult],
        [],
      ),
    'updateTerms' : IDL.Func([TermsDocument], [], []),
    'validateJoinToken' : IDL.Func(
        [IDL.Text, IDL.Text],
        [JoinTokenValidationResult],
        [],
      ),
    'validateSessionCode' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [ValidateCodeResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };