/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface FieldSource {
    value: string;
    sourceUrl: string;
}
export interface ExtendedContactDetails {
    content: string;
    contactType: LookupProvider;
    details: ContactDetails;
}
export type LocationShareResult = {
    __kind__: "error";
    error: LocationShareError;
} | {
    __kind__: "success";
    success: null;
} | {
    __kind__: "rateLimited";
    rateLimited: RateLimitError;
};
export interface LocationShareError {
    retryAfter?: bigint;
    message: string;
}
export interface ContactDetails {
    id: string;
    verified: string;
    country: string;
    validationSource?: FieldSource;
    type: string;
    trustScore: string;
    riskScoreDescription: string;
    trustScoreSource?: FieldSource;
    countryValidationSource?: FieldSource;
    address?: string;
    reports: string;
    reportsSource?: FieldSource;
    adjustedRiskScore?: string;
    riskLevel: string;
    riskScore: string;
    adjustedRiskScoreSource?: FieldSource;
}
export interface RiskRequest {
    riskHistory?: Array<bigint>;
    analyzerType: RiskAnalyzerType;
    data?: string;
    target?: string;
    businessProfile?: string;
}
export interface AnalysisResult {
    riskHistory?: Array<bigint>;
    explanation: string;
    score: number;
    businessProfile?: string;
    recommendation: string;
    riskLevel: string;
}
export interface ProviderConfig {
    endpoint?: string;
    name: LookupProvider;
    enabled: boolean;
    apiKey?: string;
}
export interface RiskAnalysis {
    riskHistory?: Array<bigint>;
    explanation: string;
    score: number;
    businessProfile?: string;
    recommendation: string;
    riskLevel: string;
}
export interface RateLimitError {
    retryAfterSeconds: bigint;
    message: string;
}
export interface AnalysisRequest {
    riskHistory?: Array<bigint>;
    analyzerType: RiskAnalyzerType;
    data?: string;
    target?: string;
    businessProfile?: string;
}
export type AnalysisResponse = {
    __kind__: "result";
    result: AnalysisResult;
} | {
    __kind__: "error";
    error: AnalysisError;
};
export interface AnalysisError {
    message: string;
    details?: string;
}
export interface TermsDocument {
    legalText: string;
    version: string;
}
export type LookupProvider = {
    __kind__: "numLookup";
    numLookup: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "google";
    google: null;
} | {
    __kind__: "amazon";
    amazon: null;
};
export type RiskResponse = {
    __kind__: "result";
    result: RiskAnalysis;
} | {
    __kind__: "error";
    error: AnalysisError;
};
export interface UserProfile {
    name: string;
}
export interface TrustedContact {
    id: bigint;
    verified: string;
    verificationDate?: string;
    contactType: string;
    validationSource?: string;
    name: string;
    extraInfo?: string;
    trustScoreSource?: string;
    details?: string;
    reportsSource?: string;
    riskLevel: string;
    lookupProvider: string;
    riskScore?: bigint;
    normalizedContact: string;
}
export enum JoinSessionResult {
    ok = "ok",
    invalidCode = "invalidCode",
    sessionNotFound = "sessionNotFound"
}
export enum JoinTokenValidationResult {
    incorrectCode = "incorrectCode",
    success = "success",
    invalidToken = "invalidToken",
    sessionNotFound = "sessionNotFound"
}
export enum RiskAnalyzerType {
    email = "email",
    crypto = "crypto",
    message = "message",
    phone = "phone"
}
export enum SessionStatus {
    active = "active",
    expired = "expired",
    pending = "pending",
    stopped = "stopped",
    ended = "ended"
}
export enum TargetType {
    email = "email",
    crypto = "crypto",
    message = "message",
    phoneNumber = "phoneNumber"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum ValidateCodeResult {
    invalidCode = "invalidCode",
    success = "success",
    sessionNotFound = "sessionNotFound"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTrustedContact(trustedContact: TrustedContact): Promise<bigint>;
    analyze(request: RiskRequest): Promise<RiskResponse>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCryptoReports(address: string): Promise<void>;
    clearPhoneReports(phone: string): Promise<void>;
    clearTrustedContacts(): Promise<void>;
    createLocationShareSession(phoneNumber1: string, phoneNumber2: string, code: string, joinToken: string): Promise<[bigint, string, boolean]>;
    endSession(sessionId: bigint): Promise<void>;
    getAllTrustedContacts(): Promise<Array<TrustedContact>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCryptoReports(address: string): Promise<bigint | null>;
    getCurrentTerms(): Promise<TermsDocument>;
    getLookupDetails(key: string): Promise<ExtendedContactDetails | null>;
    getPhoneReports(phone: string): Promise<bigint | null>;
    getProviderConfig(name: string): Promise<ProviderConfig | null>;
    getSessionLocations(sessionId: bigint): Promise<[Location | null, Location | null]>;
    getSessionStatus(sessionId: bigint): Promise<SessionStatus>;
    getTrustedContactById(id: bigint): Promise<TrustedContact | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(user: Principal): Promise<UserRole>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(code: string): Promise<JoinSessionResult>;
    oldAnalyze(request: AnalysisRequest): Promise<AnalysisResponse>;
    recordConsent(sessionId: bigint, phoneNumber: string): Promise<boolean>;
    report(targetType: TargetType, target: string, category: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setProviderConfig(name: string, config: ProviderConfig): Promise<void>;
    stopSharing(sessionId: bigint): Promise<boolean>;
    updateLocation(sessionId: bigint, phoneNumber: string, loc: Location): Promise<LocationShareResult>;
    updateTerms(newTerms: TermsDocument): Promise<void>;
    validateJoinToken(joinToken: string, confirmationCode: string): Promise<JoinTokenValidationResult>;
    validateSessionCode(sessionId: bigint, code: string): Promise<ValidateCodeResult>;
}
import type { AnalysisError as _AnalysisError, AnalysisRequest as _AnalysisRequest, AnalysisResponse as _AnalysisResponse, AnalysisResult as _AnalysisResult, ContactDetails as _ContactDetails, ExtendedContactDetails as _ExtendedContactDetails, FieldSource as _FieldSource, JoinSessionResult as _JoinSessionResult, JoinTokenValidationResult as _JoinTokenValidationResult, Location as _Location, LocationShareError as _LocationShareError, LocationShareResult as _LocationShareResult, LookupProvider as _LookupProvider, ProviderConfig as _ProviderConfig, RateLimitError as _RateLimitError, RiskAnalysis as _RiskAnalysis, RiskAnalyzerType as _RiskAnalyzerType, RiskRequest as _RiskRequest, RiskResponse as _RiskResponse, SessionStatus as _SessionStatus, TargetType as _TargetType, TrustedContact as _TrustedContact, UserProfile as _UserProfile, UserRole as _UserRole, ValidateCodeResult as _ValidateCodeResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTrustedContact(arg0: TrustedContact): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrustedContact(to_candid_TrustedContact_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrustedContact(to_candid_TrustedContact_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async analyze(arg0: RiskRequest): Promise<RiskResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.analyze(to_candid_RiskRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RiskResponse_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyze(to_candid_RiskRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RiskResponse_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCryptoReports(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCryptoReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCryptoReports(arg0);
            return result;
        }
    }
    async clearPhoneReports(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPhoneReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPhoneReports(arg0);
            return result;
        }
    }
    async clearTrustedContacts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTrustedContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTrustedContacts();
            return result;
        }
    }
    async createLocationShareSession(arg0: string, arg1: string, arg2: string, arg3: string): Promise<[bigint, string, boolean]> {
        if (this.processError) {
            try {
                const result = await this.actor.createLocationShareSession(arg0, arg1, arg2, arg3);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLocationShareSession(arg0, arg1, arg2, arg3);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async endSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endSession(arg0);
            return result;
        }
    }
    async getAllTrustedContacts(): Promise<Array<TrustedContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrustedContacts();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrustedContacts();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoReports(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoReports(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoReports(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentTerms(): Promise<TermsDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTerms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTerms();
            return result;
        }
    }
    async getLookupDetails(arg0: string): Promise<ExtendedContactDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLookupDetails(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLookupDetails(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhoneReports(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhoneReports(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhoneReports(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderConfig(arg0: string): Promise<ProviderConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderConfig(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderConfig(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionLocations(arg0: bigint): Promise<[Location | null, Location | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionLocations(arg0);
                return [
                    from_candid_opt_n35(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_opt_n35(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionLocations(arg0);
            return [
                from_candid_opt_n35(this._uploadFile, this._downloadFile, result[0]),
                from_candid_opt_n35(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async getSessionStatus(arg0: bigint): Promise<SessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionStatus(arg0);
                return from_candid_SessionStatus_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionStatus(arg0);
            return from_candid_SessionStatus_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrustedContactById(arg0: bigint): Promise<TrustedContact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrustedContactById(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrustedContactById(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: string): Promise<JoinSessionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0);
                return from_candid_JoinSessionResult_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0);
            return from_candid_JoinSessionResult_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async oldAnalyze(arg0: AnalysisRequest): Promise<AnalysisResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.oldAnalyze(to_candid_AnalysisRequest_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AnalysisResponse_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.oldAnalyze(to_candid_AnalysisRequest_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AnalysisResponse_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordConsent(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordConsent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordConsent(arg0, arg1);
            return result;
        }
    }
    async report(arg0: TargetType, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.report(to_candid_TargetType_n45(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.report(to_candid_TargetType_n45(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setProviderConfig(arg0: string, arg1: ProviderConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProviderConfig(arg0, to_candid_ProviderConfig_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProviderConfig(arg0, to_candid_ProviderConfig_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async stopSharing(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.stopSharing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopSharing(arg0);
            return result;
        }
    }
    async updateLocation(arg0: bigint, arg1: string, arg2: Location): Promise<LocationShareResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocation(arg0, arg1, arg2);
                return from_candid_LocationShareResult_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocation(arg0, arg1, arg2);
            return from_candid_LocationShareResult_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTerms(arg0: TermsDocument): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTerms(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTerms(arg0);
            return result;
        }
    }
    async validateJoinToken(arg0: string, arg1: string): Promise<JoinTokenValidationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validateJoinToken(arg0, arg1);
                return from_candid_JoinTokenValidationResult_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateJoinToken(arg0, arg1);
            return from_candid_JoinTokenValidationResult_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSessionCode(arg0: bigint, arg1: string): Promise<ValidateCodeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSessionCode(arg0, arg1);
                return from_candid_ValidateCodeResult_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSessionCode(arg0, arg1);
            return from_candid_ValidateCodeResult_n58(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisError_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisError): AnalysisError {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisResponse_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResponse): AnalysisResponse {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisResult_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ContactDetails_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactDetails): ContactDetails {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ExtendedContactDetails_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedContactDetails): ExtendedContactDetails {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_JoinSessionResult_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinSessionResult): JoinSessionResult {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_JoinTokenValidationResult_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinTokenValidationResult): JoinTokenValidationResult {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_LocationShareError_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationShareError): LocationShareError {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_LocationShareResult_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocationShareResult): LocationShareResult {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_LookupProvider_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LookupProvider): LookupProvider {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderConfig_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderConfig): ProviderConfig {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RiskAnalysis_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskAnalysis): RiskAnalysis {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_RiskResponse_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskResponse): RiskResponse {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_TrustedContact_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrustedContact): TrustedContact {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ValidateCodeResult_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidateCodeResult): ValidateCodeResult {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<bigint>]): Array<bigint> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedContactDetails]): ExtendedContactDetails | null {
    return value.length === 0 ? null : from_candid_ExtendedContactDetails_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FieldSource]): FieldSource | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProviderConfig]): ProviderConfig | null {
    return value.length === 0 ? null : from_candid_ProviderConfig_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrustedContact]): TrustedContact | null {
    return value.length === 0 ? null : from_candid_TrustedContact_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskHistory: [] | [Array<bigint>];
    explanation: string;
    score: number;
    businessProfile: [] | [string];
    recommendation: string;
    riskLevel: string;
}): {
    riskHistory?: Array<bigint>;
    explanation: string;
    score: number;
    businessProfile?: string;
    recommendation: string;
    riskLevel: string;
} {
    return {
        riskHistory: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.riskHistory)),
        explanation: value.explanation,
        score: value.score,
        businessProfile: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.businessProfile)),
        recommendation: value.recommendation,
        riskLevel: value.riskLevel
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    message: string;
    details: [] | [string];
}): {
    message: string;
    details?: string;
} {
    return {
        message: value.message,
        details: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.details))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    verified: string;
    verificationDate: [] | [string];
    contactType: string;
    validationSource: [] | [string];
    name: string;
    extraInfo: [] | [string];
    trustScoreSource: [] | [string];
    details: [] | [string];
    reportsSource: [] | [string];
    riskLevel: string;
    lookupProvider: string;
    riskScore: [] | [bigint];
    normalizedContact: string;
}): {
    id: bigint;
    verified: string;
    verificationDate?: string;
    contactType: string;
    validationSource?: string;
    name: string;
    extraInfo?: string;
    trustScoreSource?: string;
    details?: string;
    reportsSource?: string;
    riskLevel: string;
    lookupProvider: string;
    riskScore?: bigint;
    normalizedContact: string;
} {
    return {
        id: value.id,
        verified: value.verified,
        verificationDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.verificationDate)),
        contactType: value.contactType,
        validationSource: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.validationSource)),
        name: value.name,
        extraInfo: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.extraInfo)),
        trustScoreSource: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.trustScoreSource)),
        details: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.details)),
        reportsSource: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.reportsSource)),
        riskLevel: value.riskLevel,
        lookupProvider: value.lookupProvider,
        riskScore: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.riskScore)),
        normalizedContact: value.normalizedContact
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    contactType: _LookupProvider;
    details: _ContactDetails;
}): {
    content: string;
    contactType: LookupProvider;
    details: ContactDetails;
} {
    return {
        content: value.content,
        contactType: from_candid_LookupProvider_n27(_uploadFile, _downloadFile, value.contactType),
        details: from_candid_ContactDetails_n29(_uploadFile, _downloadFile, value.details)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    verified: string;
    country: string;
    validationSource: [] | [_FieldSource];
    type: string;
    trustScore: string;
    riskScoreDescription: string;
    trustScoreSource: [] | [_FieldSource];
    countryValidationSource: [] | [_FieldSource];
    address: [] | [string];
    reports: string;
    reportsSource: [] | [_FieldSource];
    adjustedRiskScore: [] | [string];
    riskLevel: string;
    riskScore: string;
    adjustedRiskScoreSource: [] | [_FieldSource];
}): {
    id: string;
    verified: string;
    country: string;
    validationSource?: FieldSource;
    type: string;
    trustScore: string;
    riskScoreDescription: string;
    trustScoreSource?: FieldSource;
    countryValidationSource?: FieldSource;
    address?: string;
    reports: string;
    reportsSource?: FieldSource;
    adjustedRiskScore?: string;
    riskLevel: string;
    riskScore: string;
    adjustedRiskScoreSource?: FieldSource;
} {
    return {
        id: value.id,
        verified: value.verified,
        country: value.country,
        validationSource: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.validationSource)),
        type: value.type,
        trustScore: value.trustScore,
        riskScoreDescription: value.riskScoreDescription,
        trustScoreSource: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.trustScoreSource)),
        countryValidationSource: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.countryValidationSource)),
        address: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.address)),
        reports: value.reports,
        reportsSource: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.reportsSource)),
        adjustedRiskScore: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.adjustedRiskScore)),
        riskLevel: value.riskLevel,
        riskScore: value.riskScore,
        adjustedRiskScoreSource: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.adjustedRiskScoreSource))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endpoint: [] | [string];
    name: _LookupProvider;
    enabled: boolean;
    apiKey: [] | [string];
}): {
    endpoint?: string;
    name: LookupProvider;
    enabled: boolean;
    apiKey?: string;
} {
    return {
        endpoint: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.endpoint)),
        name: from_candid_LookupProvider_n27(_uploadFile, _downloadFile, value.name),
        enabled: value.enabled,
        apiKey: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.apiKey))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retryAfter: [] | [bigint];
    message: string;
}): {
    retryAfter?: bigint;
    message: string;
} {
    return {
        retryAfter: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.retryAfter)),
        message: value.message
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    numLookup: null;
} | {
    custom: string;
} | {
    google: null;
} | {
    amazon: null;
}): {
    __kind__: "numLookup";
    numLookup: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "google";
    google: null;
} | {
    __kind__: "amazon";
    amazon: null;
} {
    return "numLookup" in value ? {
        __kind__: "numLookup",
        numLookup: value.numLookup
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "google" in value ? {
        __kind__: "google",
        google: value.google
    } : "amazon" in value ? {
        __kind__: "amazon",
        amazon: value.amazon
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    stopped: null;
} | {
    ended: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "expired" in value ? SessionStatus.expired : "pending" in value ? SessionStatus.pending : "stopped" in value ? SessionStatus.stopped : "ended" in value ? SessionStatus.ended : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    invalidCode: null;
} | {
    sessionNotFound: null;
}): JoinSessionResult {
    return "ok" in value ? JoinSessionResult.ok : "invalidCode" in value ? JoinSessionResult.invalidCode : "sessionNotFound" in value ? JoinSessionResult.sessionNotFound : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _AnalysisResult;
} | {
    error: _AnalysisError;
}): {
    __kind__: "result";
    result: AnalysisResult;
} | {
    __kind__: "error";
    error: AnalysisError;
} {
    return "result" in value ? {
        __kind__: "result",
        result: from_candid_AnalysisResult_n44(_uploadFile, _downloadFile, value.result)
    } : "error" in value ? {
        __kind__: "error",
        error: from_candid_AnalysisError_n13(_uploadFile, _downloadFile, value.error)
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: _LocationShareError;
} | {
    success: null;
} | {
    rateLimited: _RateLimitError;
}): {
    __kind__: "error";
    error: LocationShareError;
} | {
    __kind__: "success";
    success: null;
} | {
    __kind__: "rateLimited";
    rateLimited: RateLimitError;
} {
    return "error" in value ? {
        __kind__: "error",
        error: from_candid_LocationShareError_n54(_uploadFile, _downloadFile, value.error)
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "rateLimited" in value ? {
        __kind__: "rateLimited",
        rateLimited: value.rateLimited
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incorrectCode: null;
} | {
    success: null;
} | {
    invalidToken: null;
} | {
    sessionNotFound: null;
}): JoinTokenValidationResult {
    return "incorrectCode" in value ? JoinTokenValidationResult.incorrectCode : "success" in value ? JoinTokenValidationResult.success : "invalidToken" in value ? JoinTokenValidationResult.invalidToken : "sessionNotFound" in value ? JoinTokenValidationResult.sessionNotFound : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidCode: null;
} | {
    success: null;
} | {
    sessionNotFound: null;
}): ValidateCodeResult {
    return "invalidCode" in value ? ValidateCodeResult.invalidCode : "success" in value ? ValidateCodeResult.success : "sessionNotFound" in value ? ValidateCodeResult.sessionNotFound : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _RiskAnalysis;
} | {
    error: _AnalysisError;
}): {
    __kind__: "result";
    result: RiskAnalysis;
} | {
    __kind__: "error";
    error: AnalysisError;
} {
    return "result" in value ? {
        __kind__: "result",
        result: from_candid_RiskAnalysis_n9(_uploadFile, _downloadFile, value.result)
    } : "error" in value ? {
        __kind__: "error",
        error: from_candid_AnalysisError_n13(_uploadFile, _downloadFile, value.error)
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrustedContact>): Array<TrustedContact> {
    return value.map((x)=>from_candid_TrustedContact_n18(_uploadFile, _downloadFile, x));
}
function to_candid_AnalysisRequest_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalysisRequest): _AnalysisRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LookupProvider_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LookupProvider): _LookupProvider {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_ProviderConfig_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProviderConfig): _ProviderConfig {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_RiskAnalyzerType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskAnalyzerType): _RiskAnalyzerType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RiskRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskRequest): _RiskRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TargetType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetType): _TargetType {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_TrustedContact_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrustedContact): _TrustedContact {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    verified: string;
    verificationDate?: string;
    contactType: string;
    validationSource?: string;
    name: string;
    extraInfo?: string;
    trustScoreSource?: string;
    details?: string;
    reportsSource?: string;
    riskLevel: string;
    lookupProvider: string;
    riskScore?: bigint;
    normalizedContact: string;
}): {
    id: bigint;
    verified: string;
    verificationDate: [] | [string];
    contactType: string;
    validationSource: [] | [string];
    name: string;
    extraInfo: [] | [string];
    trustScoreSource: [] | [string];
    details: [] | [string];
    reportsSource: [] | [string];
    riskLevel: string;
    lookupProvider: string;
    riskScore: [] | [bigint];
    normalizedContact: string;
} {
    return {
        id: value.id,
        verified: value.verified,
        verificationDate: value.verificationDate ? candid_some(value.verificationDate) : candid_none(),
        contactType: value.contactType,
        validationSource: value.validationSource ? candid_some(value.validationSource) : candid_none(),
        name: value.name,
        extraInfo: value.extraInfo ? candid_some(value.extraInfo) : candid_none(),
        trustScoreSource: value.trustScoreSource ? candid_some(value.trustScoreSource) : candid_none(),
        details: value.details ? candid_some(value.details) : candid_none(),
        reportsSource: value.reportsSource ? candid_some(value.reportsSource) : candid_none(),
        riskLevel: value.riskLevel,
        lookupProvider: value.lookupProvider,
        riskScore: value.riskScore ? candid_some(value.riskScore) : candid_none(),
        normalizedContact: value.normalizedContact
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    riskHistory?: Array<bigint>;
    analyzerType: RiskAnalyzerType;
    data?: string;
    target?: string;
    businessProfile?: string;
}): {
    riskHistory: [] | [Array<bigint>];
    analyzerType: _RiskAnalyzerType;
    data: [] | [string];
    target: [] | [string];
    businessProfile: [] | [string];
} {
    return {
        riskHistory: value.riskHistory ? candid_some(value.riskHistory) : candid_none(),
        analyzerType: to_candid_RiskAnalyzerType_n5(_uploadFile, _downloadFile, value.analyzerType),
        data: value.data ? candid_some(value.data) : candid_none(),
        target: value.target ? candid_some(value.target) : candid_none(),
        businessProfile: value.businessProfile ? candid_some(value.businessProfile) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endpoint?: string;
    name: LookupProvider;
    enabled: boolean;
    apiKey?: string;
}): {
    endpoint: [] | [string];
    name: _LookupProvider;
    enabled: boolean;
    apiKey: [] | [string];
} {
    return {
        endpoint: value.endpoint ? candid_some(value.endpoint) : candid_none(),
        name: to_candid_LookupProvider_n50(_uploadFile, _downloadFile, value.name),
        enabled: value.enabled,
        apiKey: value.apiKey ? candid_some(value.apiKey) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetType): {
    email: null;
} | {
    crypto: null;
} | {
    message: null;
} | {
    phoneNumber: null;
} {
    return value == TargetType.email ? {
        email: null
    } : value == TargetType.crypto ? {
        crypto: null
    } : value == TargetType.message ? {
        message: null
    } : value == TargetType.phoneNumber ? {
        phoneNumber: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "numLookup";
    numLookup: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "google";
    google: null;
} | {
    __kind__: "amazon";
    amazon: null;
}): {
    numLookup: null;
} | {
    custom: string;
} | {
    google: null;
} | {
    amazon: null;
} {
    return value.__kind__ === "numLookup" ? {
        numLookup: value.numLookup
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "google" ? {
        google: value.google
    } : value.__kind__ === "amazon" ? {
        amazon: value.amazon
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskAnalyzerType): {
    email: null;
} | {
    crypto: null;
} | {
    message: null;
} | {
    phone: null;
} {
    return value == RiskAnalyzerType.email ? {
        email: null
    } : value == RiskAnalyzerType.crypto ? {
        crypto: null
    } : value == RiskAnalyzerType.message ? {
        message: null
    } : value == RiskAnalyzerType.phone ? {
        phone: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
